# Generated by Django 4.2.20 on 2025-04-06 17:00

import cloudinary.models
from django.db import migrations
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_patient_profile_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doctor",
            name="profile_picture",
            field=cloudinary.models.CloudinaryField(
                default=1, max_length=255, verbose_name="images"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="patient",
            name="profile_picture",
            field=cloudinary.models.CloudinaryField(
                default=django.utils.timezone.now, max_length=255, verbose_name="images"
            ),
            preserve_default=False,
        ),
    ]
