# Generated by Django 4.2.20 on 2025-03-30 10:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("review", "0004_doctorreview_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaignreview",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="campaignreview",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
