# Generated by Django 4.2.20 on 2025-03-30 10:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("review", "0005_campaignreview_created_at_campaignreview_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctorreview",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="doctorreview",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
