# Generated by Django 4.2.20 on 2025-03-27 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(name="Booking",),
    ]
